name: Tests
on: [ push, pull_request ]
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Checks
          - { name: 'Lint',        tox: lint }
          - { name: 'mypy',        tox: mypy }
          - { name: 'twine check', tox: twine }
          # Tests
          - { name: 'Python 3.6', tox: py36, python: '3.6' }
          - { name: 'Python 3.7', tox: py37, python: '3.7' }
          - { name: 'Python 3.8', tox: py38, python: '3.8' }
          - { name: 'Python 3.9', tox: py39, python: '3.9' }
          - { name: 'Python 3.10', tox: py310, python: '3.10' }
          - { name: 'Python 3.11', tox: py311, python: '3.11' }
          - { name: 'Python 3.12', tox: py312, python: '3.12' }
          - { name: 'Windows, Python 3.9',
              os: 'windows-latest',
              tox: py39, python: '3.9' }
          # Docs
          - { name: 'Docs', tox: docs }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python || '3.8' }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U wheel
          pip install -U setuptools
          pip install tox==3

      - name: Run tox -e ${{ matrix.tox }}
        run: tox -e ${{ matrix.tox }}

      - name: Install and run codecov (py38 only)
        if: ${{ matrix.tox == 'py38' }}
        run: |
          pip install codecov
          codecov

